swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Planner"
host: "localhost"
basePath: "/"
tags:
- name: "Todos"
- name: "Appointments"
- name: "Notes"
schemes:
- "https"
- "http"
paths:
  /todos:
    post:
      tags:
      - "Todos"
      summary: "Create new todo"
      operationId: "addTodo"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        "201":
          description: "Todo created"
        "405":
          description: "Invalid input"
    put:
      tags:
      - "Todos"
      summary: "Update an existing todo"
      operationId: "updateTodo"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object to update"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        "404":
          description: "Todo not found"
        "400":
          description: "Input validation failure"
definitions:
  Todo:
    type: "object"
    required:
    - "checked"
    - "priority"
    - "task"
    properties:
      id:
        type: "integer"
        format: "int64"
      checked:
        type: "boolean"
      priority:
        type: "string"
        enum:
        - "high"
        - "medium"
        - "low"
      task:
        type: "string"
        example: "Finish homework"